### PR TITLE
Migrations for skills, mentors_skills tables

### LINKED ISSUE #66: Databases: Create Migrations for Users, Skills, Mentor_Skills, and Organisations
Create the Knex Migrations in order to create the DB schema for the following tables:

 Users, Skills, Mentor_Skills, and Organisations  - Topic Green

Screenshot 2020-11-22 at 15 21 34

Please consider the DB Diagram - https://dbdiagram.io/d/5fb801913a78976d7b7cc7d8

### PR DESCRIPTION
**Pull request by Deepti-Dk**
# Description

This PR is about create the Knex Migrations for skills, mentors_skills tables.  Dropped 'organizations' table as a separate PR for 'users' and 'organizations' is being created.
-by Yaser, Maher and Deepti (Green Team)

Fixes #66 

# How to test?

tested in workbench and tables are created in in schema

# Checklist

- [] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by yukafjaponesa — DISMISSED** [review]
looks nice with the existing code.

**Review by bytewiz — COMMENTED** [review]
What is the reason for deleting this seed file @Deepti-Dk ?

`src/server/seeds/development/skills.js`

**Comment by Deepti-Dk** [comment]
> What is the reason for deleting this seed file @Deepti-Dk ?
> 
> `src/server/seeds/development/skills.js`

There is a separate PR for seeding...for all tables together. Daniel advised to keep migrations and seeding separate.

**Review by tpetrina — APPROVED** [review]
Good stuff, merge it!

**Review by nuha90 — APPROVED** [review]

**Pull request merged**
