### PR TITLE
Feature/avatar improvement

### PR DESCRIPTION
**Pull request by Yaser-Aldammad**
# Description

improved the radius property to go along with Appheader
Fixes # (issue)

# How to test?

tested by storybook
# Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by tpetrina — COMMENTED** [review]
If you commit this, you might break your colleagues with merge conflicts. Are you sure you want to do this?

**Comment by Yaser-Aldammad** [comment]
So shall I will wait until I finish the whole component and then you see the effect of the improvement on the component

**Comment by tpetrina** [comment]
@Yaser-Aldammad That's up to you, you are all in this together.

**Comment by MaherHussain** [comment]
closing this PR

**Pull request closed without merging**
