### PR TITLE
DateTime component

### LINKED ISSUE #20: Storybook: Day time picker
When I am want to create a new study group, I want to be able to to enter a new Date and Time for that specific study group.

Create a Storybook Day time picker inspired on the examples here https://react-day-picker.js.org/

image

Create the component with the appropriate style and make sure that it works for Desktop and Mobile.

Please check the resources here https://www.figma.com/file/9gN79UmpDPrAZk5jY4V7Ww/Study-Group-Management-System?node-id=0%3A1

### PR DESCRIPTION
**Pull request by Deepti-Dk**
# Description

Added the DateTime component through installing React DateTime package

Fixes #20 

# How to test?

can be tested through storybook

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by tpetrina — APPROVED** [review]
Great work - I'd love it if you didn't add prettier in this PR. Could you remove it please?

**Comment by Deepti-Dk** [comment]
> Great work - I'd love it if you didn't add prettier in this PR. Could you remove it please?

Really, I didn't add prettier! It could be from the package I installed, will remove it hoping nothing breaks. Thanks

**Comment by Pallabi-ghosh** [comment]
Hi Toni, I have seen my class-mate installed date and time picker that update the `package.json` also, its update `Prettier` as well. So, should we keep as it is when we will pull or remove the Prettier?  which is already included in our Final-project.

Screenshot 2020-11-20 at 11 58 14

**Comment by tpetrina** [comment]
`package.json` is only updated by running `npm i packagename` command.

**Review by tpetrina — APPROVED** [review]

**Review by MaherHussain — APPROVED** [review]
great

**Pull request merged**
