### PR TITLE
Migrations for Events, Event_users, Event_students, Event_mentors tables

### LINKED ISSUE #64: Databases: Create Migrations for Events, Event_users, Event_students, Event_mentors and Questions
Create the Knex Migrations in order to create the DB schema for the following tables:

Events, Event_users, Event_students, Event_mentors and Questions  - Topic Blue

Screenshot 2020-11-22 at 15 21 34

Please consider the DB Diagram - https://dbdiagram.io/d/5fb801913a78976d7b7cc7d8

### PR DESCRIPTION
**Pull request by claudion3**
# Description

This PR is about create the Knex Migrations for Events, Event_users, Event_students, Event_mentors tables.
@nuha90 made Event_users
@AnilMula made Event_students
@Kiran-Serolla made Events
@claudion3 made Event_mentors

Fixes #64 

# How to test?
events
events_students
events_users
events_users

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by dpfernandes — CHANGES_REQUESTED** [review]
I would like to see migrations on a separate PR from seeding.

Please try to put yourselves on the Reviewer shoes :) If it's separate it's easier to review and you will get it merged faster.

Imagine that there is an error on one register on one seeding table file - the PR will not be merged and that means that 4 tables and 4 seeding files are on hold because of one single typo or mistake

**Review by dpfernandes — CHANGES_REQUESTED** [review]
Missing **deleted_at** on events_mentors

**Review by Deepti-Dk — COMMENTED** [review]
Writing these comments based on the diagram and my knowledge(limited) so please wait for feedback from the mentor just to be sure about these. Thanks

events_students
-----------------------
'eventsStudents' table name to 'events_students'

'eventId' to 'event_id'
'studentId' to 'student_id'
'createdAt' to 'created_at'
'updatedAt' to 'updated_at'
'deletedAt' to 'deleted_at'

events_users
--------------
'usersId' to 'users_id'
'createdAt' to 'created_at'
'updatedAt' to 'updated_at'
'deletedAt' to 'deleted_at'

**Review by bytewiz — APPROVED** [review]
Looks good to me 👍 a nice description of the Pull Request 👍

**Pull request closed without merging**
